/**
 * src/lib/sitemap.ts
 * ─────────────────────────────────────────────────────────
 * Sitemap utility — classifies scanned + generated pages into groups,
 * builds the per-group sitemap XML, and builds the master sitemap
 * index. Consumed by src/pages/sitemap-*.xml.ts SSR endpoints.
 *
 * Two path sources are merged:
 *   1. src/data/sitemap-pages.generated.ts — AUTO-GENERATED by the
 *      sitemapAutoScan integration in astro.config.mjs from static
 *      .astro files (do not edit the generated file by hand). Dynamic
 *      routes ([slug].astro, [...slug].astro) are skipped by that scan.
 *   2. dynamicPaths() below — derived from the SAME typed data files
 *      (conditions.ts, services.ts, locations.ts) that feed each
 *      dynamic route's getStaticPaths, so this list can never drift
 *      from what actually gets built.
 *
 * To add a new group: extend `groupMeta` + add a pattern match in
 * `classify()`, then create src/pages/sitemap-<slug>.xml.ts. That's it.
 */

import { sitemapPaths } from '../data/sitemap-pages.generated';
import { conditionCategories } from '../data/conditions';
import { services } from '../data/services';
import { locations } from '../data/locations';
import { teamMembers } from '../data/team';

/**
 * Real URLs for every dynamic-route page, derived from the same data
 * that drives each template's getStaticPaths (see astro.config.mjs
 * for why the file scanner can't discover these itself).
 */
function dynamicPaths(): string[] {
  const conditionPaths = new Set<string>();
  for (const category of conditionCategories) {
    conditionPaths.add(category.href);
    for (const condition of category.conditions) conditionPaths.add(condition.href);
  }

  const servicePaths = services.map((s) => s.href);
  const locationPaths = locations.flatMap((l) => [l.clinicHref, l.pricesHref]);
  const teamPaths = teamMembers.map((m) => `/team/${m.slug}/`);

  return [...conditionPaths, ...servicePaths, ...locationPaths, ...teamPaths];
}

// ── Group metadata ─────────────────────────────────────────────
// Order of keys here is the order they appear in the sitemap index.
export const groupMeta = {
  core: {
    slug:       'core',
    priority:   '1.0',
    changefreq: 'weekly',
  },
  about: {
    slug:       'about',
    priority:   '0.8',
    changefreq: 'monthly',
  },
  team: {
    slug:       'team',
    priority:   '0.8',
    changefreq: 'monthly',
  },
  services: {
    slug:       'services',
    priority:   '0.9',
    changefreq: 'weekly',
  },
  conditions: {
    slug:       'conditions',
    priority:   '0.8',
    changefreq: 'monthly',
  },
  legal: {
    slug:       'legal',
    priority:   '0.4',
    changefreq: 'yearly',
  },
  support: {
    slug:       'support',
    priority:   '0.6',
    changefreq: 'monthly',
  },
} as const;

export type GroupKey = keyof typeof groupMeta;

// Convenience object so endpoints can use `groups.services` etc.
export const groups = Object.fromEntries(
  Object.keys(groupMeta).map((k) => [k, k])
) as { [K in GroupKey]: K };

// ── Classification ─────────────────────────────────────────────
/**
 * First-match-wins path-pattern classifier. Keep the rules ordered
 * from most-specific to least-specific. Unmatched paths fall through
 * to `support` so nothing silently disappears from the sitemap.
 */
function classify(path: string): GroupKey {
  if (path === '/') return 'core';

  // Legal / policy pages
  if (
    path.startsWith('/privacy-policy')   ||
    path.startsWith('/terms-conditions') ||
    path.startsWith('/cookie-policy')    ||
    path.startsWith('/accessibility')
  ) return 'legal';

  // Team page
  if (path.startsWith('/team')) return 'team';

  // About / company / clinic-location pages
  if (
    path.startsWith('/about')      ||
    path.startsWith('/contact')    ||
    path.startsWith('/clinics')    ||
    path.startsWith('/faqs')       ||
    path.startsWith('/join-our-team') ||
    path.startsWith('/appointments')
  ) return 'about';

  // Services + prices (pricing is a service-adjacent commercial page)
  if (
    path.startsWith('/service/') ||
    path.startsWith('/prices')
  ) return 'services';

  // Conditions ("What We Treat" taxonomy) — /conditions/ listing +
  // /condition/{category}/{leaf} inner pages.
  if (path.startsWith('/condition')) return 'conditions';

  // Fallback — keeps everything discoverable
  return 'support';
}

/**
 * Group the scanned paths into a `{ groupKey: string[] }` lookup.
 * Computed once at module load (sitemapPaths is frozen at build time).
 */
function groupPaths(): Record<GroupKey, string[]> {
  const byGroup: Record<GroupKey, string[]> = {
    core:       [],
    about:      [],
    team:       [],
    services:   [],
    conditions: [],
    legal:      [],
    support:    [],
  };
  const allPaths = new Set([...sitemapPaths, ...dynamicPaths()]);
  for (const p of allPaths) {
    byGroup[classify(p)].push(p);
  }
  return byGroup;
}

const grouped = groupPaths();

/** Returns the list of non-empty group keys — used by the sitemap index. */
export function populatedGroups(): GroupKey[] {
  return (Object.keys(grouped) as GroupKey[]).filter((k) => grouped[k].length > 0);
}

// ── XML builders ───────────────────────────────────────────────
const HMDG_CREDIT = '<!-- Generated by HMDG | hmdg.co.uk -->';

function xmlEscape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Build a per-group <urlset> sitemap. Origin is picked up from
 * `Astro.url.origin` inside each SSR endpoint so localhost /
 * *.workers.dev / production domain all produce correctly-rooted URLs.
 */
export function buildSitemapXml(origin: string, group: GroupKey): string {
  const meta  = groupMeta[group];
  const paths = grouped[group];
  const today = new Date().toISOString().slice(0, 10);

  const urls = paths.map((p) => `  <url>
    <loc>${xmlEscape(origin + p)}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${meta.changefreq}</changefreq>
    <priority>${meta.priority}</priority>
  </url>`).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
${HMDG_CREDIT}
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

/**
 * Build the master sitemap index referencing all populated group
 * sitemaps. Skips empty groups automatically.
 */
export function buildSitemapIndexXml(origin: string): string {
  const today = new Date().toISOString().slice(0, 10);
  const entries = populatedGroups().map((g) => `  <sitemap>
    <loc>${xmlEscape(`${origin}/sitemap-${groupMeta[g].slug}.xml`)}</loc>
    <lastmod>${today}</lastmod>
  </sitemap>`).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
${HMDG_CREDIT}
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</sitemapindex>
`;
}
